const messages = 
["	Confusion say, baby born in car with automatic transmission, grow to become shiftless bastard	",
"	Confusion say, baseball wrong. Man with four balls not able to walk	",
"	Confusion say, better to be pissed off than pissed on	",
"	Confusion say, boy who go to sleep with sex problem on mind wake up with solution in hand	",
"	Confusion say, butcher who back into meat grinder get a little behind in his orders	",
"	Confusion say, couple on seven day honeymoon make whole week	",
"	Confusion say, cow with no legs, ground beef	",
"	Confusion say, finding old man in dark, not hard	",
"	Confusion say, foolish man give wife grand piano, wise man give wife upright organ	",
"	Confusion say, girl who ride bicycle, peddle ass all over town	",
"	Confusion say, girl who sit on jockey's lap get hot tip	",
"	Confusion say, girl who sit on judge's lap get honorable discharge	",
"	Confusion say, house without bathroom is uncanny	",
"	Confusion say, if you want pretty nurse, you got to be patient	",
"	Confusion say, it take many nail to build crib, one screw to fill it	",
"	Confusion say, man piss in wind, wind piss back	",
"	Confusion say, man trapped in pantry, have ass in jam	",
"	Confusion say, man under wheelbarrow playing with tool, not necessarily mechanic	",
"	Confusion say, man who do business in whore house get jerked around	",
"	Confusion say, man who drive like hell, bound to get there	",
"	Confusion say, man who drop watch in toilet have crappy time	",
"	Confusion say, man who eat crackers in bed wake up feeling crummy	",
"	Confusion say, man who eat too many prunes, get good run for money	",
"	Confusion say, man who ejaculate in cash register come into money	",
"	Confusion say, man who fall in vat of molten glass, make spectacle of self	",
"	Confusion say, man who fart in church, sit in own pew	",
"	Confusion say, man who fight with wife all day, get no piece at night	",
"	Confusion say, man who fishes in another woman's well, often catches crab	",
"	Confusion say, man who get kicked in testicles, left holding the bag	",
"	Confusion say, man who go to bed with itchy butt wake up with smelly fingers	",
"	Confusion say, man who have last laugh, not get joke	",
"	Confusion say, man who jump through screen door, strain self	",
"	Confusion say, man who keep feet on ground have trouble putting on pants	",
"	Confusion say, man who kisses girl's behind, get crack in face	",
"	Confusion say, man who leap off cliff jump to conclusion	",
"	Confusion say, man who live in glass house, should change in basement	",
"	Confusion say, man who make love on side of hill not on level	",
"	Confusion say, man who masturbate, only screwing himself	",
"	Confusion say, man who push piano down mine shaft, likely to get A flat minor	",
"	Confusion say, man who put cock on stove, have hot rod	",
"	Confusion say, man who put face in punchbowl, get punch in nose	",
"	Confusion say, man who put pea in soup very unclean	",
"	Confusion say, man who run before bus get tired	",
"	Confusion say, man who run behind bus get exhausted	",
"	Confusion say, man who run through airport turnstile backward going to Bangkok	",
"	Confusion say, man who shoot off mouth, must expect to lose face	",
"	Confusion say, man who sit on tack, get point	",
"	Confusion say, man who sits on stool smells like crap	",
"	Confusion say, man who sleep in bed of nails is holy	",
"	Confusion say, man who smoke pot, choke on handle	",
"	Confusion say, man who snort coke, get bubbles up nose	",
"	Confusion say, man who stand on toilet high on pot	",
"	Confusion say, man who throws dirt is losing ground	",
"	Confusion say, man with athletic finger, make broad jump	",
"	Confusion say, man with big mouth beware of foot	",
"	Confusion say, man with hand in pocket all day not crazy, just feeling nuts	",
"	Confusion say, man with head on railroad track, listening for train to come, get splitting headache	",
"	Confusion say, man with hole in pocket feel cocky all day long	",
"	Confusion say, man with tool in woman's mouth not necessarily dentist	",
"	Confusion say, men may have more hair on chest than woman, but on the whole, women have more	",
"	Confusion say, OK for crap to happen - will decompose	",
"	Confusion say, passionate kiss like spider web, soon lead to undoing of fly	",
"	Confusion say, sex is like the army, the closer you are to discharge, the better you feel	",
"	Confusion say, squirrel who runs up woman's leg not find nuts	",
"	Confusion say, support bacteria - is only culture some people have	",
"	Confusion say, to meet girl in park is good, but to park meat in girl is better	",
"	Confusion say, two wrongs not make right, but two rights make U-turn	",
"	Confusion say, virginity like bubble. One prick - all gone	",
"	Confusion say, waitress who sit on lepper's lap, keep tip	",
"	Confusion say, war not determine who right. War determine who left	",
"	Confusion say, woman wearing G-string, high on crack	",
"	Confusion say, woman who dance wearing jock strap, have make believe ballroom	",
"	Confusion say, woman who fly upside down have crack up	",
"	Confusion say, woman who go camping must beware of evil intent	",
"	Confusion say, woman who sink in man's arms, soon have arms in man's sink	",
"	Confusion say, woman who spend much time on bedspring, may get offspring	"]

//const messageDiv = document.getElementById("message");
//document.getElementById('btn').addEventListener('click', getMessage());


function getMessageIndex() {
    return Math.floor(Math.random(0, 1) * (messages.length));
}

function getMessage() {
    let randomMessage = messages[getMessageIndex()];
    document.getElementById('message').textContent = randomMessage;
}